
import { Translation, Language } from './types';

export const ADMIN_ID = "8215056224"; 
export const BOT_TOKEN = "8543158894:AAHkaN83tLCgNrJ-Omutn744aTui784GScc";
export const BOT_ADMIN_ID = "8215056224";

// To'lov uchun karta ma'lumotlari
export const CARD_DETAILS = "8600 0000 0000 0000";
export const CARD_HOLDER = "RUSLAN M.";

export const translations: Record<Language, Translation> = {
  uz: {
    welcome: "Ruslan Market",
    login: "Kirish",
    enterId: "Mijoz ID",
    enterPhone: "Telefon raqam",
    start: "Boshlash",
    home: "Asosiy",
    trackers: "Treklar",
    profile: "Profil",
    settings: "Sozlamalar",
    addTrack: "Trek qo'shish",
    trackPlaceholder: "Trek raqamini kiriting",
    invalidTrack: "Trek raqami xato",
    stats: "Statistika",
    totalWeight: "Umumiy kg",
    totalPaid: "Jami to'lov",
    tier: "Daraja",
    language: "Til",
    theme: "Mavzu",
    adminPanel: "Admin Panel",
    updateWeight: "Kg va Narx qo'shish",
    save: "Saqlash",
    pricePerKg: "1 kg narxi",
    loyaltyFriend: "Do'st",
    loyaltyDear: "Qadirdon",
    loyaltyPartner: "Hamkor",
    pay: "To'lov qilish",
    paymentDetails: "To'lov ma'lumotlari",
    confirmPayment: "To'ladim",
    awaitingVerification: "Tekshirilmoqda",
  },
  ru: {
    welcome: "Ruslan Market",
    login: "Вход",
    enterId: "ID Клиента",
    enterPhone: "Телефон",
    start: "Начать",
    home: "Главная",
    trackers: "Треки",
    profile: "Профиль",
    settings: "Настройки",
    addTrack: "Добавить трек",
    trackPlaceholder: "Введите трек номер",
    invalidTrack: "Ошибка номера",
    stats: "Статистика",
    totalWeight: "Общий вес",
    totalPaid: "Итого",
    tier: "Уровень",
    language: "Язык",
    theme: "Тема",
    adminPanel: "Админ",
    updateWeight: "Добавить вес и цену",
    save: "Сохранить",
    pricePerKg: "Цена за кг",
    loyaltyFriend: "Друг",
    loyaltyDear: "Дорогой",
    loyaltyPartner: "Партнер",
    pay: "Оплатить",
    paymentDetails: "Детали оплаты",
    confirmPayment: "Я оплатил",
    awaitingVerification: "Проверка",
  },
  en: {
    welcome: "Ruslan Market",
    login: "Login",
    enterId: "Client ID",
    enterPhone: "Phone Number",
    start: "Start",
    home: "Home",
    trackers: "Trackers",
    profile: "Profile",
    settings: "Settings",
    addTrack: "Add Track",
    trackPlaceholder: "Enter track number",
    invalidTrack: "Invalid track number",
    stats: "Statistics",
    totalWeight: "Total KG",
    totalPaid: "Total Paid",
    tier: "Tier",
    language: "Language",
    theme: "Theme",
    adminPanel: "Admin Panel",
    updateWeight: "Update weight & price",
    save: "Save",
    pricePerKg: "Price per kg",
    loyaltyFriend: "Friend",
    loyaltyDear: "Dear",
    loyaltyPartner: "Partner",
    pay: "Pay Now",
    paymentDetails: "Payment details",
    confirmPayment: "Confirmed",
    awaitingVerification: "Verifying",
  }
};
